"""empty message

Revision ID: 47b3c918d274
Revises: f5026c67d089
Create Date: 2023-05-01 11:14:25.957446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b3c918d274'
down_revision = 'f5026c67d089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=64), nullable=False))
        batch_op.drop_constraint('posts_authour_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author'], ['email'])
        batch_op.drop_column('authour')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authour', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('posts_authour_fkey', 'users', ['authour'], ['email'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###
